### ISSUE TITLE
/search does not return anything

### ISSUE THREAD

**Issue by quisquous** [thewakingsands/cafemaker#1]
We're trying to use xivapi and cafemaker to do automatic translations of ffxiv content.  See: https://github.com/quisquous/cactbot/pull/872

https://xivapi.com/search?string=doom
https://cafemaker.wakingsands.com/search?string=doom

The search on cafemaker doesn't return anything.

**Comment by oott123** [comment]
I'm sorry for that but our search is currently Chinese-optimized, which means, we only index Chinese contents.
You can get Chinese search result like this:

https://cafemaker.wakingsands.com/search?string=%E6%AD%BB%E4%BA%A1%E5%AE%A3%E5%91%8A

However, I'm very happy to solve that issue but I want to know your use case so that I can give a better solution.

Currently, cafemaker is targeted to the china version, so it just contains an out-dated database for global servers; for now, we Chinese users are playing 5.05 while global is 5.18. So using cafemaker for global translation is not a good idea.

How about this: you do your search using xivapi.com, and then get the ideal URL, like `/Action/86`; 
and then get the full content from cafemaker: https://cafemaker.wakingsands.com/Action/86 . If the later page responds, you can get `Name_chs` from it for Chinese translation.

**Comment by oott123** [comment]
I read the code from quisquous/cactbot#872. Can we just send 2 requests [here](https://github.com/quisquous/cactbot/pull/872/files#diff-dc71daa0fe51de2ff195f1294bcce932R128), one to xivapi and one to cafemaker, for Chinese translation?

**Comment by JLGarber** [comment]
We could, for actions. However, the context in which we are searching for NPCs or debuffs doesn't have those IDs. (If we did we would just issue a single request for each category with all the IDs included.) Going to XIVAPI first for the ID was an extra step we were hoping to avoid, but it's understandable if updating the search to accommodate English isn't possible at this time.

**Comment by oott123** [comment]
@JLGarber I'm afraid that going to xivapi is the only way.

As I said before, cafemaker is a database only contains contents matching Chinese latest version (for now, 5.05, is an outdated version if you are playing  FFXIV NA/JP or so), and we don't have any way to keep it updated because:

* Different versions have different database struct.
* China versions are updated after about 3 months, and we can only get translations then.

If we do can keep it update, we do not need to fork xivapi.

Anyway, update translations is an automatically progress, which doesn't require by users but only required by maintainers, so making more requests won't be a significate issue in my opinion.

BTW, we also maintained a repo that contains all Chinese data sheets extracted by SaintCoinach in CSV format. Maybe you can use this to avoid some requests if that fits your case.

**Comment by oott123** [comment]
Let me confirm: I'm saying that searching translations **only** from cafemaker (without XIVAPI) is impossible because it's tied to the Chinese version. I'm not saying it's impossible to fix this so we can search in English in this outdated database. It's possible but I think that have no help for you.

Please point me out if I have misunderstood something, and sorry for my bad English.

**Comment by JLGarber** [comment]
No, that's a perfectly fine explanation, it's far better than anything I could put together in a non-English language. I was not aware when I started on this that there were limitations that would make the techniques I had in mind effectively impossible. Now that I know, we can make the necessary adjustments on the translation script.

Thanks for taking the time to explain all this to us!

(@quisquous did you have anything to add that I may have missed?)

**Comment by quisquous** [comment]
I think you make a really good point--it makes more sense to do the searching on xivapi for ids and then only do direct lookups on cafemaker, especially because of the difference in release schedules.

I think there was some hope on our end that we could treat both sites the same and not have special cases (or maybe that we misunderstood how search worked on cafemaker vs xiapi), but I do not think this is a big deal and is something we can handle.  I just wanted to check with you first.

Thanks for the confirmation that searching does work, but that there's only Chinese indexes.  That explains a lot.  Thanks also for the link to that other repo of exported files.  That's quite helpful to know about.

Thanks for all the feedback.  I'll close this issue now, as I don't think there's anything else to follow up about.
